import {
  parseFeatureContract,
  parseProjectContract,
  type ActionContract,
  type FeatureContract,
  type FormBinding,
  type ProjectContract,
  type PropertySchema,
} from "@0disoft/mensor-contract";

import type { DraftField } from "./draft-form.js";
import { InputFailure } from "./paths.js";
import type { DraftContractFile } from "./types.js";

const identifierPattern = /^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/u;
const routePattern = /^\/[^?#]*$/u;

export function assertDraftIdentifier(
  value: string,
  label: string,
  code: string,
): string {
  if (!identifierPattern.test(value)) {
    throw new InputFailure(
      "configuration",
      code,
      `${label} must match ${identifierPattern.source}.`,
    );
  }
  return value;
}

export function assertDraftRoute(
  value: string,
  label: string,
  code: string,
): string {
  if (!routePattern.test(value)) {
    throw new InputFailure(
      "configuration",
      code,
      `${label} must be a static root-relative path without a query or fragment.`,
    );
  }
  return value;
}

export function createContractDrafts(options: {
  readonly actionId?: string;
  readonly configFile: string;
  readonly documentPath?: string;
  readonly featureConfigFile: string;
  readonly featureId: string;
  readonly fields: readonly DraftField[];
  readonly formId: string;
  readonly formTemplate: string;
  readonly handlerExport: string;
  readonly handlerFile: string;
  readonly handlerRole: string;
  readonly handlerRoot: string;
  readonly routePath: string;
  readonly sourceRoot: string;
}): {
  readonly actionId: string;
  readonly project: DraftContractFile;
  readonly feature: DraftContractFile;
} {
  const actionId = options.actionId === undefined
    ? createDefaultActionId(options.featureId, options.formId)
    : assertDraftIdentifier(
        options.actionId,
        "actionId",
        "init.action_id_invalid",
      );
  const feature = createFeatureContract({ ...options, actionId });
  const project: ProjectContract = {
    version: 1,
    sourceRoot: options.sourceRoot,
    featureContracts: [options.featureConfigFile],
    fileRoles: [
      {
        role: options.handlerRole,
        withinFeature: options.handlerRoot,
      },
    ],
  };
  assertGeneratedContracts(project, feature);
  return {
    actionId,
    project: {
      path: options.configFile,
      content: serializeDraft(
        [
          "Generated by mensor init from explicit feature and handler-role choices.",
          "Review fileRoles before treating this draft as architectural policy.",
        ],
        project,
      ),
    },
    feature: {
      path: options.featureConfigFile,
      content: serializeDraft(
        [
          "Generated by mensor init from static HTML and explicit runtime exports.",
          "Fields are optional text values by default; review requiredness and decoders.",
        ],
        feature,
      ),
    },
  };
}

function createFeatureContract(options: {
  readonly actionId: string;
  readonly documentPath?: string;
  readonly featureId: string;
  readonly fields: readonly DraftField[];
  readonly formId: string;
  readonly formTemplate: string;
  readonly handlerExport: string;
  readonly handlerFile: string;
  readonly handlerRole: string;
  readonly routePath: string;
}): FeatureContract {
  const properties: Record<string, PropertySchema> = Object.fromEntries(
    options.fields.map((field): [string, PropertySchema] => [
      field.name,
      field.repeated
        ? { kind: "array", items: { kind: "string" } }
        : { kind: "string" },
    ]),
  );
  const bindings: FormBinding[] = options.fields.map((field) => ({
    name: field.name,
    path: [field.name],
    decode: field.repeated
      ? {
          kind: "repeat",
          items: { kind: "text", trim: false, empty: "allow" },
        }
      : { kind: "text", trim: false, empty: "allow" },
  }));
  const action: ActionContract = {
    id: options.actionId,
    route: { method: "POST", path: options.routePath },
    form: {
      template: options.formTemplate,
      id: options.formId,
      ...(options.documentPath === undefined
        ? {}
        : { documentPath: options.documentPath }),
    },
    handler: {
      file: options.handlerFile,
      export: options.handlerExport,
      role: options.handlerRole,
    },
    input: {
      schema: { kind: "object", properties, required: [] },
      formCodec: {
        encoding: "urlencoded",
        unknownFields: "reject",
        bindings,
      },
    },
  };
  return {
    version: 1,
    feature: { id: options.featureId },
    actions: [action],
  };
}

function assertGeneratedContracts(
  project: ProjectContract,
  feature: FeatureContract,
): void {
  const projectResult = parseProjectContract(`${JSON.stringify(project)}\n`);
  const featureResult = parseFeatureContract(`${JSON.stringify(feature)}\n`);
  if (!projectResult.ok || !featureResult.ok) {
    throw new Error("Generated contract draft failed its public parser.");
  }
}

function serializeDraft(
  comments: readonly string[],
  value: ProjectContract | FeatureContract,
): string {
  return `${comments.map((comment) => `// ${comment}`).join("\n")}\n${JSON.stringify(value, null, 2)}\n`;
}

function createDefaultActionId(featureId: string, formId: string): string {
  const segment = formId
    .replace(/[A-Z]/gu, (character) => character.toLowerCase())
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-+|-+$/gu, "");
  if (segment.length === 0) {
    throw new InputFailure(
      "configuration",
      "init.action_id_required",
      `Form id ${JSON.stringify(formId)} cannot produce a Mensor action id. Supply --action-id explicitly.`,
    );
  }
  const safeSegment = /^[a-z]/u.test(segment) ? segment : `form-${segment}`;
  return assertDraftIdentifier(
    `${featureId}.${safeSegment}`,
    "generated action id",
    "init.action_id_invalid",
  );
}
