import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  parseFeatureContract,
  parseProjectContract,
} from "../../contract/dist/src/index.js";

const executable = fileURLToPath(new URL("../dist/src/bin.js", import.meta.url));

const initArguments = [
  "init",
  "--feature-root",
  "src/features/guestbook",
  "--feature-id",
  "guestbook",
  "--handler-role",
  "server",
];

test("creates reviewable drafts and the generated project passes check", async (t) => {
  const root = await createProject();
  t.after(() => rm(root, { force: true, recursive: true }));

  const initialized = await runCli(initArguments, root);
  assert.equal(initialized.code, 0);
  assert.equal(initialized.stderr, "");
  assert.match(initialized.stdout, /Created mensor\.project\.jsonc/u);
  assert.match(initialized.stdout, /Selected form .*#create-entry/u);
  assert.match(initialized.stdout, /Selected handler .*#createEntry/u);

  const projectText = await readFile(
    path.join(root, "mensor.project.jsonc"),
    "utf8",
  );
  const featureText = await readFile(
    path.join(root, "src/features/guestbook/feature.mensor.jsonc"),
    "utf8",
  );
  assert.match(projectText, /^\/\/ Generated by mensor init/u);
  assert.match(featureText, /review requiredness and decoders/u);
  assert.equal(parseProjectContract(projectText).ok, true);
  assert.equal(parseFeatureContract(featureText).ok, true);

  const checked = await runCli(["check", "--json"], root);
  assert.equal(checked.code, 0);
  assert.equal(checked.stderr, "");
  assert.equal(JSON.parse(checked.stdout).status, "passed");
});

test("refuses overwrites without changing existing drafts", async (t) => {
  const root = await createProject();
  t.after(() => rm(root, { force: true, recursive: true }));

  const first = await runCli(initArguments, root);
  assert.equal(first.code, 0);
  const projectPath = path.join(root, "mensor.project.jsonc");
  const featurePath = path.join(
    root,
    "src/features/guestbook/feature.mensor.jsonc",
  );
  const beforeProject = await readFile(projectPath, "utf8");
  const beforeFeature = await readFile(featurePath, "utf8");

  const second = await runCli(initArguments, root);
  assert.equal(second.code, 2);
  assert.equal(second.stdout, "");
  assert.match(second.stderr, /init\.output_exists/u);
  assert.equal(await readFile(projectPath, "utf8"), beforeProject);
  assert.equal(await readFile(featurePath, "utf8"), beforeFeature);
});

test("rolls back the feature draft when project publication fails", async (t) => {
  const root = await createProject();
  t.after(() => rm(root, { force: true, recursive: true }));
  const projectPath = path.join(root, "mensor.project.jsonc");
  await writeFile(projectPath, "existing project contract\n", "utf8");

  const result = await runCli(initArguments, root);
  assert.equal(result.code, 2);
  assert.equal(result.stdout, "");
  assert.match(result.stderr, /init\.output_exists/u);
  assert.equal(await readFile(projectPath, "utf8"), "existing project contract\n");
  const featureDirectory = path.join(root, "src/features/guestbook");
  assert.deepEqual(
    (await readdir(featureDirectory)).filter((name) => name.includes("mensor")),
    [],
  );
});

test("requires selector options in complete pairs", async (t) => {
  const root = await createProject();
  t.after(() => rm(root, { force: true, recursive: true }));

  const result = await runCli(
    [...initArguments, "--form-file", "src/features/guestbook/views/index.html"],
    root,
  );
  assert.equal(result.code, 2);
  assert.equal(result.stdout, "");
  assert.match(result.stderr, /--form-file and --form-id must be supplied together/u);
});

async function createProject() {
  const root = await mkdtemp(path.join(tmpdir(), "mensor-cli-init-"));
  const featureRoot = path.join(root, "src/features/guestbook");
  await mkdir(path.join(featureRoot, "server"), { recursive: true });
  await mkdir(path.join(featureRoot, "views"), { recursive: true });
  await writeFile(
    path.join(featureRoot, "views/index.html"),
    '<form id="create-entry" method="post" action="/guestbook"><input name="author"></form>\n',
    "utf8",
  );
  await writeFile(
    path.join(featureRoot, "server/create-entry.ts"),
    'throw new Error("must not execute");\nexport function createEntry() {}\n',
    "utf8",
  );
  return root;
}

async function runCli(args, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [executable, ...args], {
      cwd,
      env: {},
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.once("error", reject);
    child.once("close", (code, signal) => {
      if (signal !== null) {
        reject(new Error(`CLI terminated by signal ${signal}.`));
        return;
      }
      resolve({ code, stdout, stderr });
    });
  });
}
